Linux default installation path is now the users home dir

diff --git a/JonDonym/trunk/install_jondo b/JonDonym/trunk/install_jondo
--- a/JonDonym/trunk/install_jondo
+++ b/JonDonym/trunk/install_jondo
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 ## Copyright (c) The JAP-Team, JonDos GmbH
 ##
@@ -28,17 +28,34 @@
 ## NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ## SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ##
-##   JonDo client installation script
+##   JonDo client installation script for bash
 ##   2008 by Simon Pecher, JonDos GmbH (simon.pecher@jondos.de)
 ##
 
-#INSTALL_PATH can be set as environment variable
-INSTALL_PATH=${INSTALL_PATH}
+#default INSTALL_PATH is the users home directory
+INSTALL_PATH=${HOME}
 
 #set placeholders for ant token filtering
+#these values should be set by ant
 ARGS="@ARGS@" 
 APPNAME="@APPNAME@"
 JARNAME="@JARNAME@"
+
+#don't leave the installpath dir in a mess when errors occur.
+onErrorCleanupAndExit()
+{
+	rm -Rf "${INSTALL_PATH}/${APPNAME}"
+	echo "${APPNAME} installation failed."
+	echo ""
+	exit 1
+}
+
+errorStarter()
+{
+	echo "Error creating ${APPNAME} Starter."
+	rm -f "${STARTER}" 
+	onErrorCleanupAndExit	
+}
 
 #if no filtering was done, replace the token placeholders with default values
 args_token=$(expr "${ARGS}" : "@\(.*\)@")
@@ -56,23 +73,23 @@ if  [ "${jarname_token}" = "JARNAME" ]; then
 	JARNAME="JAP"
 fi
 
-#this is APPNAME in lowercase
+#the name of the Jondo Starter should be in lowercase
 APPNAME_LOWERCASE=$(echo "$APPNAME" | tr "[:upper:]" "[:lower:]" || echo "$APPNAME")
 
 #print help text
 if [ "$1" == "--help" ]; then
-	
+	echo ""
 	echo "${APPNAME} installation for Linux, (2008 Copyright (c) JonDos GmbH)"
-	echo "usage: $0 [ <installation path> | --help ]"
+	echo "usage: $0 [ <installpath> | --help ]"
 	echo ""
 	echo "The following files will be installed by this:"
 	echo ""
-	echo " <installation path>/${APPNAME}/${JARNAME}.jar"
-	echo " <installation path>/bin/${APPNAME_LOWERCASE}"
+	echo " <installpath>/${APPNAME}/${JARNAME}.jar"
+	echo " <installpath>/bin/${APPNAME_LOWERCASE}"
 	echo ""
-	echo "When nothing is specified the default installation path is \"/usr/local\"," 
-	echo "(which then requires root permissions). You can either specify the installation" 
-	echo "path as a command line option or as environment variable INSTALL_PATH ."
+	echo "When not specified installpath defaults to \$HOME or \"/usr/local\", if HOME is not set." 
+	echo "NOTE: if you install to a directory where certain permissions are required, the" \
+		"automatic updating of ${APPNAME} will fail unless you start it as a privileged user."
 	echo ""
 	echo "The option --help will show this info."	
 	echo ""
@@ -85,6 +102,7 @@ elif [ "${INSTALL_PATH}" = "" ]; then
 	INSTALL_PATH="/usr/local" #if nothing is set: default install path is /usr/local
 fi
 
+echo ""
 echo "Installing ${APPNAME} to ${INSTALL_PATH}"
 
 #complete path of the starter
@@ -95,8 +113,7 @@ STARTER="${STARTER_ROOT}/${APPNAME_LOWERCASE}"
 install -Dvm 755 "${JARNAME}.jar" "${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar"
 
 if [ $? -ne 0 ]; then
-	echo "Installing ${APPNAME} aborted"
-	exit 1
+	onErrorCleanupAndExit
 fi
 
 #make sure the bin dir for the JonDo starter exists
@@ -104,18 +121,26 @@ if [ -d "${STARTER_ROOT}" ]; then
 	echo "Directory ${STARTER_ROOT} exists."
 else
 	echo "creating directory ${STARTER_ROOT}"
-	mkdir "${STARTER_ROOT}" || exit 1
+	mkdir "${STARTER_ROOT}" || onErrorCleanupAndExit
 fi
 
+java -version >& /dev/null || \
+echo "WARNING: No Java VM installation found. ${APPNAME} will not be able to run without Java."
+
 #create the JonDo starter (the appname in lower case by convention)
-echo '#!/bin/sh' > ${STARTER} 	|| exit 1
-echo '' >> ${STARTER} 		|| exit 1
-echo "java -jar ${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar ${ARGS}" \
-	>> ${STARTER}	 	|| exit 1
-echo '' >> ${STARTER} 		|| exit 1
+echo '#!/bin/sh' > ${STARTER} 	|| errorStarter
+echo '' >> ${STARTER} 		|| errorStarter
+echo "java -jar ${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar ${ARGS} \$@" \
+	>> ${STARTER}	 	|| errorStarter
+echo '' >> ${STARTER} 		|| errorStarter
 
-chmod 755 ${STARTER} 		|| exit 1
+chmod 755 ${STARTER} 		|| errorStarter
 
+#everything worked fine
 echo ""
-echo "${APPNAME} successfully installed to ${INSTALL_PATH}."
-echo "Now type '${APPNAME_LOWERCASE}' to start the ${APPNAME} client. (If that won't do try '${STARTER}')"
+echo "${APPNAME} was successfully installed to ${INSTALL_PATH}."
+echo "Now type '${APPNAME_LOWERCASE}' to start the ${APPNAME} client." 
+echo "(If that won't do try '${STARTER}' or add '${STARTER_ROOT}' to your PATH variable)"
+echo ""
+
+exit 0
