Beta of the linux install script. Feel free to test it.

diff --git a/install_jondo b/install_jondo
--- a/install_jondo
+++ b/install_jondo
@@ -32,9 +32,12 @@
 ##   2008 by Simon Pecher, JonDos GmbH (simon.pecher@jondos.de)
 ##
 
+JONDOS_HOMEPAGE="https://www.jondos.de"
+
 #default INSTALL_PATH is the users home directory
 INSTALL_PATH=${HOME}
-
+JAVA_HOME_PATH=${JAVA_HOME}
+JAVA_CMD="java"
 #set placeholders for ant token filtering
 #these values should be set by ant
 ARGS="@ARGS@" 
@@ -46,7 +49,7 @@ onErrorCleanupAndExit()
 {
 	rm -Rf "${INSTALL_PATH}/${APPNAME}"
 	echo "${APPNAME} installation failed."
-	echo ""
+	echo
 	exit 1
 }
 
@@ -55,6 +58,66 @@ errorStarter()
 	echo "Error creating ${APPNAME} Starter."
 	rm -f "${STARTER}" 
 	onErrorCleanupAndExit	
+}
+
+#print help text
+printHelpText()
+{
+	echo "${APPNAME} installation for Linux, (2008 Copyright (c) JonDos GmbH, ${JONDOS_HOMEPAGE})"
+	echo "usage: $0 [options] installpath"
+	echo
+	echo "The following files will be installed:"
+	echo
+	echo " [installpath]/${APPNAME}/${JARNAME}.jar"
+	echo " [installpath]/bin/${APPNAME_LOWERCASE}"
+	echo
+	echo "If not specified installpath defaults to \$HOME or \"/usr/local\", if HOME is not set." 
+	echo
+	echo "Options are:"
+	echo "  -h -?                   shows this help text"
+	echo "  -j java_home_path       to specify the path where your java VM is installed,"
+	echo "                          (the directory of the command 'java' without the trailing 'bin')."
+	
+}
+
+javaCheck()
+{
+	$JAVA_CMD -version >& /dev/null && return 0
+	echo "WARNING: Java VM installation $JAVA_CMD not found."
+	echo "${APPNAME} will not be able to run without Java."
+	echo "You can continue with the installation but you have to set JAVA_HOME to your"\
+	     "Java VM installation path (the directory of the command 'java' without the trailing 'bin')"\
+	     "before starting jondo."
+	echo
+	echo -n "Do you want to continue? (y/n) "
+	read -n 1 jCheckanswer
+	echo
+	case ${jCheckanswer} in
+		y*) JAVA_CMD="java"
+		    JAVA_HOME_PATH="";;
+ 		*)  echo "${APPNAME} was not installed."; exit 1;;
+	esac
+	echo
+}
+
+#check if gnu classpath java is installed
+gcjCheck()
+{
+	$JAVA_CMD -version 2>&1 | grep -i gnu\ >& /dev/null
+	if [ $? -eq 0 ]; then
+		echo "WARNING: GNU Java installation found. ${APPNAME} will not be able to run with GNU Java."\
+		     "Please install a SUN JRE to run ${APPNAME}, (www.java.sun.com)."
+		echo
+		echo -n "Do you want to continue? (y/n) "
+		read -n 1 gjCheckanswer
+		echo
+		case ${gjCheckanswer} in
+			y*) JAVA_CMD="java"
+			    JAVA_HOME_PATH="";;
+ 			*)  echo "${APPNAME} was not installed."; exit 1;;
+		esac
+		echo
+	fi
 }
 
 #if no filtering was done, replace the token placeholders with default values
@@ -76,38 +139,59 @@ fi
 #the name of the Jondo Starter should be in lowercase
 APPNAME_LOWERCASE=$(echo "$APPNAME" | tr "[:upper:]" "[:lower:]" || echo "$APPNAME")
 
-#print help text
-if [ "$1" == "--help" ]; then
-	echo ""
-	echo "${APPNAME} installation for Linux, (2008 Copyright (c) JonDos GmbH)"
-	echo "usage: $0 [ <installpath> | --help ]"
-	echo ""
-	echo "The following files will be installed by this:"
-	echo ""
-	echo " <installpath>/${APPNAME}/${JARNAME}.jar"
-	echo " <installpath>/bin/${APPNAME_LOWERCASE}"
-	echo ""
-	echo "When not specified installpath defaults to \$HOME or \"/usr/local\", if HOME is not set." 
-	echo "NOTE: if you install to a directory where certain permissions are required, the" \
-		"automatic updating of ${APPNAME} will fail unless you start it as a privileged user."
-	echo ""
-	echo "The option --help will show this info."	
-	echo ""
-	exit 0
-fi
+##start of the main routine
+#read the commandline arguments
+OPTSTR="?j:h"	
+getopts "${OPTSTR}" CMD_OPT
+while [ $? -eq 0 ]; 
+do
+	case ${CMD_OPT} in
+		j)
+			JAVA_HOME_PATH=${OPTARG};;
+		h | ?)
+			printHelpText; 
+			exit 0;;
+		*)	
+			echo "unrecognized option: ${CMD_OPT}"
+		   	printHelpText
+		   	exit 1;;
+	esac
+	getopts "${OPTSTR}" CMD_OPT
+done
 
+shift $[$OPTIND-1]
 if [ "$1" != "" ]; then
 	INSTALL_PATH=$1
 elif [ "${INSTALL_PATH}" = "" ]; then
 	INSTALL_PATH="/usr/local" #if nothing is set: default install path is /usr/local
 fi
 
-echo ""
-echo "Installing ${APPNAME} to ${INSTALL_PATH}"
-
 #complete path of the starter
 STARTER_ROOT="${INSTALL_PATH}/bin"
 STARTER="${STARTER_ROOT}/${APPNAME_LOWERCASE}"
+
+#set java command for java checks
+if [ "${JAVA_HOME_PATH}" ]; then
+	JAVA_CMD=${JAVA_HOME_PATH}/bin/java 
+fi
+
+#do the java checks
+javaCheck
+gcjCheck
+
+#get the users confirmation
+echo "${APPNAME} installation for Linux, (2008 Copyright (c) JonDos GmbH, ${JONDOS_HOMEPAGE})"
+echo "Installing ${APPNAME} to ${INSTALL_PATH}, this will create:"
+echo "   1. the directory '${INSTALL_PATH}/${APPNAME}',"
+echo "   2. the file '${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar'"
+echo "   3. the file '${STARTER}'"
+echo -n "Do you want to continue? (y/n) "
+read -n 1 answer
+echo
+case ${answer} in
+	y*);;
+ 	*) echo "${APPNAME} was not installed."; exit 1;;
+esac
 
 #install JAP.jar
 install -Dvm 755 "${JARNAME}.jar" "${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar"
@@ -124,23 +208,93 @@ else
 	mkdir "${STARTER_ROOT}" || onErrorCleanupAndExit
 fi
 
-java -version >& /dev/null || \
-echo "WARNING: No Java VM installation found. ${APPNAME} will not be able to run without Java."
-
 #create the JonDo starter (the appname in lower case by convention)
-echo '#!/bin/sh' > ${STARTER} 	|| errorStarter
-echo '' >> ${STARTER} 		|| errorStarter
-echo "java -jar ${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar ${ARGS} \$@" \
-	>> ${STARTER}	 	|| errorStarter
-echo '' >> ${STARTER} 		|| errorStarter
+echo '#!/bin/bash' 								 > ${STARTER} || errorStarter
+echo  										>> ${STARTER} || errorStarter
+echo "JAVA_HOME_PATH=\"${JAVA_HOME_PATH}\""					>> ${STARTER} || errorStarter
+echo 'JAVA_CMD="java"'								>> ${STARTER} || errorStarter
+echo										>> ${STARTER} || errorStarter
+echo 'javaCheck()'								>> ${STARTER} || errorStarter
+echo '{'									>> ${STARTER} || errorStarter
+echo '   $JAVA_CMD -version >& /dev/null && return 0'				>> ${STARTER} || errorStarter
+echo '   echo "ERROR: Java VM ${JAVA_CMD} not found. Please set JAVA_HOME to the path of a valid Java VM installation"\'\
+										>> ${STARTER} || errorStarter
+echo '        "(the directory of the command \"java\" without the trailing \"bin\")."'\
+										>> ${STARTER} || errorStarter
+echo "   return 1"  								>> ${STARTER} || errorStarter
+echo '}'									>> ${STARTER} || errorStarter
+echo										>> ${STARTER} || errorStarter
+echo 'gcjCheck()'								>> ${STARTER} || errorStarter
+echo '{'									>> ${STARTER} || errorStarter
+echo '   $JAVA_CMD -version 2>&1 | grep -i gnu\ >& /dev/null || return 0;'	>> ${STARTER} || errorStarter
+echo "   echo \"ERROR: GNU Java installation found. ${APPNAME} will not be able to run with GNU Java.\"\\"\
+										>> ${STARTER} || errorStarter
+echo "        \"Please install a SUN JRE to run ${APPNAME}, (www.java.sun.com).\""\
+										>> ${STARTER} || errorStarter
+echo "   return 1"  								>> ${STARTER} || errorStarter
+echo '}'									>> ${STARTER} || errorStarter
+echo										>> ${STARTER} || errorStarter
+echo 'if [ "${JAVA_HOME}" ]; then'						>> ${STARTER} || errorStarter
+echo '   if [ "${JAVA_HOME_PATH}" -a ! "${JAVA_HOME}" -ef "${JAVA_HOME_PATH}" ]; then'\
+										>> ${STARTER} || errorStarter
+echo '      echo "WARNING: JAVA_HOME is set to ${JAVA_HOME}, your specified path ${JAVA_HOME_PATH} will be ignored."\'\
+										>> ${STARTER} || errorStarter
+echo '           "If you want to use your specified path, please undefine JAVA_HOME."'\
+										>> ${STARTER} || errorStarter
+echo '   fi'									>> ${STARTER} || errorStarter
+echo '   JAVA_HOME_PATH="${JAVA_HOME}"'						>> ${STARTER} || errorStarter
+echo 'fi'									>> ${STARTER} || errorStarter
+echo										>> ${STARTER} || errorStarter
+echo 'if [ "${JAVA_HOME_PATH}" ]; then'						>> ${STARTER} || errorStarter
+echo '   JAVA_CMD="${JAVA_HOME_PATH}/bin/java"'					>> ${STARTER} || errorStarter
+echo 'fi'									>> ${STARTER} || errorStarter
+echo										>> ${STARTER} || errorStarter
+echo 'case "$1" in' 								>> ${STARTER} || errorStarter
+echo '   --remove)'								>> ${STARTER} || errorStarter
+echo "      if [ ! -w \"${INSTALL_PATH}/${APPNAME}\" -o ! -w \"${STARTER}\" ]; then "\
+										>> ${STARTER} || errorStarter
+echo "         echo \"you are not privileged to remove ${APPNAME}, please run this again as privileged user\""\
+										>> ${STARTER} || errorStarter
+echo "         exit 1"  							>> ${STARTER} || errorStarter
+echo "      fi" 								>> ${STARTER} || errorStarter
+echo "      echo \"Uninstallling ${APPNAME}... This will delete:\""		>> ${STARTER} || errorStarter
+echo "      echo \"   1. the directory '${INSTALL_PATH}/${APPNAME}',\""		>> ${STARTER} || errorStarter
+echo "      echo \"   2. the file '${STARTER}'\""				>> ${STARTER} || errorStarter
+echo "      echo \"   3. the ${APPNAME} config and help files\""		>> ${STARTER} || errorStarter
+echo '      echo'								>> ${STARTER} || errorStarter
+echo '      echo -n "Do you want to continue? (y/n) "' 				>> ${STARTER} || errorStarter
+echo '      read -n 1 answer' 							>> ${STARTER} || errorStarter
+echo '      echo' 								>> ${STARTER} || errorStarter
+echo '      case ${answer} in' 							>> ${STARTER} || errorStarter
+echo '         y*);;'       							>> ${STARTER} || errorStarter
+echo "         *) echo \"${APPNAME} was not removed.\"; exit 1;;"  		>> ${STARTER} || errorStarter
+echo '      esac' 								>> ${STARTER} || errorStarter
+echo "      javaCheck && gcjCheck && \$JAVA_CMD -jar ${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar -s --uninstall"\
+										>> ${STARTER} || errorStarter
+echo "      rm -Rv ${INSTALL_PATH}/${APPNAME}" 					>> ${STARTER} || errorStarter
+echo '      exec rm -v $0 '							>> ${STARTER} || errorStarter
+echo '      ;;'  								>> ${STARTER} || errorStarter
+echo '   --help)'								>> ${STARTER} || errorStarter
+echo "      javaCheck && gcjCheck && \$JAVA_CMD -jar ${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar --help"\
+										>> ${STARTER} || errorStarter
+echo "      echo \"--remove                     Deletes all installed ${APPNAME} file\""\
+										>> ${STARTER} || errorStarter
+echo "      echo \"                             including directory ${INSTALL_PATH}/${APPNAME} and file ${STARTER}\";;"\
+										>> ${STARTER} || errorStarter
+echo "   *) javaCheck && gcjCheck && \$JAVA_CMD -jar ${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar ${ARGS} \$@;;"\
+										>> ${STARTER} || errorStarter
+echo 'esac' 									>> ${STARTER} || errorStarter
+echo	  									>> ${STARTER} || errorStarter
+chmod 755 									   ${STARTER} || errorStarter
 
-chmod 755 ${STARTER} 		|| errorStarter
-
-#everything worked fine
-echo ""
+#installation successful. print success message and some additional infos.
+echo
 echo "${APPNAME} was successfully installed to ${INSTALL_PATH}."
-echo "Now type '${APPNAME_LOWERCASE}' to start the ${APPNAME} client." 
-echo "(If that won't do try '${STARTER}' or add '${STARTER_ROOT}' to your PATH variable)"
-echo ""
+echo "Now type '${APPNAME_LOWERCASE}' to start the ${APPNAME} client."\
+     "(If that does not work try '${STARTER}' or add '${STARTER_ROOT}' to your PATH variable with:"\
+     "'export PATH=\${PATH}:${STARTER_ROOT}')"
+echo
+echo "With '${APPNAME_LOWERCASE} --remove' you can cleanup the ${APPNAME} installation" 
+echo "For more information type '${APPNAME_LOWERCASE} --help' or visit '${JONDOS_HOMEPAGE}'"
 
 exit 0
